services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment: DATABASE_URL=postgresql://postgres:postgres@@localhost:5432/postgres?schema=public
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

